### ISSUE TITLE
-nd's documentation is reversed

### ISSUE THREAD

**Issue by michaelcinquin** [madmickstar/restorething#1]
Hi

thanks for the great tool.

I think -nd documentation should read:
**Disable** restoring files that have been deleted or changed due to renaming, by default deleted or renamed files are ** included in restore
Not
Enables restoring files that have been deleted or changed due to renaming, by default deleted or renamed files are not included in restore

**Comment by madmickstar** [comment]
Hi michaelcinquin

Thanks for the feedback and taking the time to comment.  I have updated the doco inline with your comments and made improvement to the cli -h output as well.

**Comment by madmickstar** [comment]
master updated see v0.2.5
